export const onsets = [
  { phoneme: 'b', odds: 0 },
  { phoneme: 'bʷ', odds: 0 },
  { phoneme: 'ʃ', odds: 5 },
  { phoneme: 't͡ʃ', odds: 1 },
  { phoneme: 't͡ʃʷ', odds: 0 },
  { phoneme: 'ʒ', odds: 0 },
  { phoneme: 'd͡ʒ', odds: 0 },
  { phoneme: 'ʒʷ', odds: 0 },
  { phoneme: 'd', odds: 1 },
  { phoneme: 'f', odds: 2 },
  { phoneme: 'g', odds: 0 },
  { phoneme: 'gʷ', odds: 0 },
  { phoneme: 'x', odds: 2 },
  { phoneme: 'k', odds: 30 },
  { phoneme: 'kʷ', odds: 2 },
  { phoneme: 'l', odds: 0 },
  { phoneme: 'm', odds: 0 },
  { phoneme: 'mʷ', odds: 0 },
  { phoneme: 'n', odds: 0 },
  { phoneme: 'p', odds: 2 },
  { phoneme: 'pʷ', odds: 0 },
  { phoneme: 'ɹ', odds: 0 },
  { phoneme: 's', odds: 25 },
  { phoneme: 't', odds: 30 },
  { phoneme: 'ʔ', odds: 0 },
  { phoneme: 'w', odds: 0 },
  { phoneme: 'j', odds: 0 },
  { phoneme: 'z', odds: 5 },
  { phoneme: 'ʃm', odds: 0 },
  { phoneme: 'ʃn', odds: 0 },
  { phoneme: 'ʃp', odds: 0 },
  { phoneme: 'ʃpʷ', odds: 0 },
  { phoneme: 'ʃk', odds: 1 },
  { phoneme: 'ʃkʷ', odds: 0 },
  { phoneme: 'ʃʷ', odds: 0 },
  { phoneme: 'sm', odds: 0 },
  { phoneme: 'sn', odds: 0 },
  { phoneme: 'sp', odds: 1 },
  { phoneme: 'spʷ', odds: 0 },
  { phoneme: 'sk', odds: 3 },
  { phoneme: 'skʷ', odds: 0 },
  { phoneme: 'sʷ', odds: 0 },
];

export const codas = [
  { phoneme: 'n', odds: 0 },
  { phoneme: 'ʃ', odds: 5 },
  { phoneme: 't͡ʃ', odds: 0 },
  { phoneme: 'ʒ', odds: 0 },
  { phoneme: 'd͡ʒ', odds: 0 },
  { phoneme: 'k', odds: 20 },
  { phoneme: 'l', odds: 0 },
  { phoneme: 'p', odds: 2 },
  { phoneme: 's', odds: 15 },
  { phoneme: 't', odds: 20 },
  { phoneme: 'ʃp', odds: 0 },
  { phoneme: 'ʃk', odds: 2 },
  { phoneme: 'sp', odds: 1 },
  { phoneme: 'sk', odds: 2 },
];

export const vowels = [
  { phoneme: 'ɑ', odds: 10 },
  { phoneme: 'a', odds: 30 },
  { phoneme: 'e', odds: 0 },
  { phoneme: 'i', odds: 0 },
  { phoneme: 'o', odds: 30 },
  { phoneme: 'u', odds: 0 },
];
